// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TTOptimizer.Web.Data;

#nullable disable

namespace TTOptimizer.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813144622_AddTeacherBuildingChangePreference2")]
    partial class AddTeacherBuildingChangePreference2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("DefaultRoomId")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeroomTeacherId")
                        .HasColumnType("integer");

                    b.Property<string>("Info")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("DefaultRoomId");

                    b.HasIndex("HomeroomTeacherId");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("ClassGroups");
                });

            modelBuilder.Entity("LessonRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClassGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("HoursPerWeek")
                        .HasColumnType("integer");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<int?>("StudentGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ClassGroupId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("StudentGroupId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("LessonRequirements");
                });

            modelBuilder.Entity("OptimizationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<int>("BestPenalty")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InitialPenalty")
                        .HasColumnType("integer");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("OptimizationRuns");
                });

            modelBuilder.Entity("Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<string>("Info")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<int?>("PreferredSubjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("RestrictedToSubjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("PreferredSubjectId");

                    b.HasIndex("RestrictedToSubjectId");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("ScheduledLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<int>("LessonNumber")
                        .HasColumnType("integer");

                    b.Property<int>("OptimizationRunId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassGroupId");

                    b.HasIndex("OptimizationRunId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("ScheduledLessons");
                });

            modelBuilder.Entity("Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Info")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.AppUserOrganization", b =>
                {
                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("AppUserId", "OrganizationId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("AppUserOrganizations");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Info")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.ClassGroupSchedulingPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvoidSingleLessonDay")
                        .HasColumnType("integer");

                    b.Property<int>("ClassGroupId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxConsecutiveLessons")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxConsecutiveLessonsLimit")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxLessonsPerDay")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxLessonsPerDayLimit")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimizeGaps")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassGroupId")
                        .IsUnique();

                    b.ToTable("ClassGroupSchedulingPreferences", t =>
                        {
                            t.HasCheckConstraint("CK_ClassGroupSchedulingPreferences_MaxConsecutiveLessonsLimit", "\"MaxConsecutiveLessonsLimit\" IS NULL OR (\"MaxConsecutiveLessonsLimit\" >= 1 AND \"MaxConsecutiveLessonsLimit\" <= 8)");

                            t.HasCheckConstraint("CK_ClassGroupSchedulingPreferences_MaxLessonsPerDayLimit", "\"MaxLessonsPerDayLimit\" IS NULL OR (\"MaxLessonsPerDayLimit\" >= 1 AND \"MaxLessonsPerDayLimit\" <= 8)");
                        });
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.ClassGroupTimeSlotPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("DayIndex")
                        .HasColumnType("integer");

                    b.Property<int>("PreferenceType")
                        .HasColumnType("integer");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassGroupId", "DayIndex", "SlotIndex")
                        .IsUnique();

                    b.ToTable("ClassGroupTimeSlotPreferences", t =>
                        {
                            t.HasCheckConstraint("CK_ClassGroupTimeSlotPreference_DayIndex", "\"DayIndex\" >= 0 AND \"DayIndex\" <= 4");

                            t.HasCheckConstraint("CK_ClassGroupTimeSlotPreference_SlotIndex", "\"SlotIndex\" >= 0 AND \"SlotIndex\" <= 7");
                        });
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DirectorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.OrganizationSchedulingPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassGroupAvoidSingleLessonDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ClassGroupMaxConsecutiveLessons")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<int>("ClassGroupMaxConsecutiveLessonsLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(6);

                    b.Property<int>("ClassGroupMaxLessonsPerDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<int>("ClassGroupMaxLessonsPerDayLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(8);

                    b.Property<int>("ClassGroupMinimizeGaps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectAvoidDoubleLessons")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("SubjectMaxOccurrencesPerDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<int>("SubjectMaxOccurrencesPerDayLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("SubjectPreferDoubleLessons")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("SubjectSpreadAcrossDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<int>("TeacherAvoidImmediateBuildingChange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<int>("TeacherAvoidSingleLessonDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("TeacherMaxConsecutiveLessons")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<int>("TeacherMaxConsecutiveLessonsLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4);

                    b.Property<int>("TeacherMaxLessonsPerDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<int>("TeacherMaxLessonsPerDayLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(6);

                    b.Property<int>("TeacherMinimizeGaps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("OrganizationSchedulingPreferences", t =>
                        {
                            t.HasCheckConstraint("CK_OrganizationSchedulingPreferences_ClassGroupMaxConsecutiveLessonsLimit", "\"ClassGroupMaxConsecutiveLessonsLimit\" >= 1 AND \"ClassGroupMaxConsecutiveLessonsLimit\" <= 8");

                            t.HasCheckConstraint("CK_OrganizationSchedulingPreferences_ClassGroupMaxLessonsPerDayLimit", "\"ClassGroupMaxLessonsPerDayLimit\" >= 1 AND \"ClassGroupMaxLessonsPerDayLimit\" <= 8");

                            t.HasCheckConstraint("CK_OrganizationSchedulingPreferences_MaxConsecutiveLessonsLimit", "\"TeacherMaxConsecutiveLessonsLimit\" >= 1 AND \"TeacherMaxConsecutiveLessonsLimit\" <= 8");

                            t.HasCheckConstraint("CK_OrganizationSchedulingPreferences_MaxLessonsPerDayLimit", "\"TeacherMaxLessonsPerDayLimit\" >= 1 AND \"TeacherMaxLessonsPerDayLimit\" <= 8");

                            t.HasCheckConstraint("CK_OrganizationSchedulingPreferences_SubjectMaxOccurrencesPerDayLimit", "\"SubjectMaxOccurrencesPerDayLimit\" >= 1 AND \"SubjectMaxOccurrencesPerDayLimit\" <= 8");
                        });
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.RoomTimeSlotPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayIndex")
                        .HasColumnType("integer");

                    b.Property<int>("PreferenceType")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "DayIndex", "SlotIndex")
                        .IsUnique();

                    b.ToTable("RoomTimeSlotPreferences", t =>
                        {
                            t.HasCheckConstraint("CK_RoomTimeSlotPreference_DayIndex", "\"DayIndex\" >= 0 AND \"DayIndex\" <= 4");

                            t.HasCheckConstraint("CK_RoomTimeSlotPreference_SlotIndex", "\"SlotIndex\" >= 0 AND \"SlotIndex\" <= 7");
                        });
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.ScheduleConstraint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConstraintType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsHard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<int?>("SlotNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100);

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("ScheduleConstraints");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.StudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassGroupId")
                        .HasColumnType("integer");

                    b.Property<int?>("DivisionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassGroupId")
                        .IsUnique()
                        .HasFilter("\"Type\" = 0");

                    b.HasIndex("DivisionId");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("StudentGroups");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.StudentGroupDivision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ClassGroupId", "Name")
                        .IsUnique();

                    b.ToTable("StudentGroupDivisions");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.StudentGroupMember", b =>
                {
                    b.Property<int>("StudentGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("MemberGroupId")
                        .HasColumnType("integer");

                    b.HasKey("StudentGroupId", "MemberGroupId");

                    b.HasIndex("MemberGroupId");

                    b.ToTable("StudentGroupMembers");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.SubjectSchedulingPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvoidDoubleLessons")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxOccurrencesPerDay")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxOccurrencesPerDayLimit")
                        .HasColumnType("integer");

                    b.Property<int?>("PreferDoubleLessons")
                        .HasColumnType("integer");

                    b.Property<int?>("SpreadAcrossDays")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId")
                        .IsUnique();

                    b.ToTable("SubjectSchedulingPreferences", t =>
                        {
                            t.HasCheckConstraint("CK_SubjectSchedulingPreferences_MaxOccurrencesPerDayLimit", "\"MaxOccurrencesPerDayLimit\" IS NULL OR (\"MaxOccurrencesPerDayLimit\" >= 1 AND \"MaxOccurrencesPerDayLimit\" <= 8)");
                        });
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.SubjectTimeSlotPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayIndex")
                        .HasColumnType("integer");

                    b.Property<int>("PreferenceType")
                        .HasColumnType("integer");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "DayIndex", "SlotIndex")
                        .IsUnique();

                    b.ToTable("SubjectTimeSlotPreferences", t =>
                        {
                            t.HasCheckConstraint("CK_SubjectTimeSlotPreference_DayIndex", "\"DayIndex\" >= 0 AND \"DayIndex\" <= 4");

                            t.HasCheckConstraint("CK_SubjectTimeSlotPreference_SlotIndex", "\"SlotIndex\" >= 0 AND \"SlotIndex\" <= 7");
                        });
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.TeacherSchedulingPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvoidSingleLessonDay")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxConsecutiveLessons")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxConsecutiveLessonsLimit")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxLessonsPerDay")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxLessonsPerDayLimit")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimizeGaps")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId")
                        .IsUnique();

                    b.ToTable("TeacherSchedulingPreferences", t =>
                        {
                            t.HasCheckConstraint("CK_TeacherSchedulingPreferences_MaxConsecutiveLessonsLimit", "\"MaxConsecutiveLessonsLimit\" IS NULL OR (\"MaxConsecutiveLessonsLimit\" >= 1 AND \"MaxConsecutiveLessonsLimit\" <= 8)");

                            t.HasCheckConstraint("CK_TeacherSchedulingPreferences_MaxLessonsPerDayLimit", "\"MaxLessonsPerDayLimit\" IS NULL OR (\"MaxLessonsPerDayLimit\" >= 1 AND \"MaxLessonsPerDayLimit\" <= 8)");
                        });
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.TeacherTimeSlotPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayIndex")
                        .HasColumnType("integer");

                    b.Property<int>("PreferenceType")
                        .HasColumnType("integer");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId", "DayIndex", "SlotIndex")
                        .IsUnique();

                    b.ToTable("TeacherTimeSlotPreferences", t =>
                        {
                            t.HasCheckConstraint("CK_TeacherTimeSlotPreference_DayIndex", "\"DayIndex\" >= 0 AND \"DayIndex\" <= 4");

                            t.HasCheckConstraint("CK_TeacherTimeSlotPreference_SlotIndex", "\"SlotIndex\" >= 0 AND \"SlotIndex\" <= 7");
                        });
                });

            modelBuilder.Entity("Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Info")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("OrganizationId", "Alias")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "TeacherNumber")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("ClassGroup", b =>
                {
                    b.HasOne("TTOptimizer.Web.Models.Domain.AppUser", null)
                        .WithMany("ClassGroups")
                        .HasForeignKey("AppUserId");

                    b.HasOne("Room", "DefaultRoom")
                        .WithMany()
                        .HasForeignKey("DefaultRoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Teacher", "HomeroomTeacher")
                        .WithMany()
                        .HasForeignKey("HomeroomTeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TTOptimizer.Web.Models.Domain.Organization", "Organization")
                        .WithMany("ClassGroups")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultRoom");

                    b.Navigation("HomeroomTeacher");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("LessonRequirement", b =>
                {
                    b.HasOne("TTOptimizer.Web.Models.Domain.AppUser", null)
                        .WithMany("LessonRequirements")
                        .HasForeignKey("AppUserId");

                    b.HasOne("ClassGroup", "ClassGroup")
                        .WithMany()
                        .HasForeignKey("ClassGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TTOptimizer.Web.Models.Domain.Organization", "Organization")
                        .WithMany("LessonRequirements")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTOptimizer.Web.Models.Domain.StudentGroup", "StudentGroup")
                        .WithMany()
                        .HasForeignKey("StudentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassGroup");

                    b.Navigation("Organization");

                    b.Navigation("StudentGroup");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("OptimizationRun", b =>
                {
                    b.HasOne("TTOptimizer.Web.Models.Domain.AppUser", null)
                        .WithMany("OptimizationRuns")
                        .HasForeignKey("AppUserId");

                    b.HasOne("TTOptimizer.Web.Models.Domain.Organization", "Organization")
                        .WithMany("OptimizationRuns")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Room", b =>
                {
                    b.HasOne("TTOptimizer.Web.Models.Domain.AppUser", null)
                        .WithMany("Rooms")
                        .HasForeignKey("AppUserId");

                    b.HasOne("TTOptimizer.Web.Models.Domain.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TTOptimizer.Web.Models.Domain.Organization", "Organization")
                        .WithMany("Rooms")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Subject", "PreferredSubject")
                        .WithMany()
                        .HasForeignKey("PreferredSubjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Subject", "RestrictedToSubject")
                        .WithMany()
                        .HasForeignKey("RestrictedToSubjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Building");

                    b.Navigation("Organization");

                    b.Navigation("PreferredSubject");

                    b.Navigation("RestrictedToSubject");
                });

            modelBuilder.Entity("ScheduledLesson", b =>
                {
                    b.HasOne("ClassGroup", "ClassGroup")
                        .WithMany()
                        .HasForeignKey("ClassGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptimizationRun", "OptimizationRun")
                        .WithMany("ScheduledLessons")
                        .HasForeignKey("OptimizationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassGroup");

                    b.Navigation("OptimizationRun");

                    b.Navigation("Room");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Subject", b =>
                {
                    b.HasOne("TTOptimizer.Web.Models.Domain.AppUser", null)
                        .WithMany("Subjects")
                        .HasForeignKey("AppUserId");

                    b.HasOne("TTOptimizer.Web.Models.Domain.Organization", "Organization")
                        .WithMany("Subjects")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.AppUserOrganization", b =>
                {
                    b.HasOne("TTOptimizer.Web.Models.Domain.AppUser", "AppUser")
                        .WithMany("AppUserOrganizations")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTOptimizer.Web.Models.Domain.Organization", "Organization")
                        .WithMany("AppUserOrganizations")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.Building", b =>
                {
                    b.HasOne("TTOptimizer.Web.Models.Domain.Organization", "Organization")
                        .WithMany("Buildings")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.ClassGroupSchedulingPreferences", b =>
                {
                    b.HasOne("ClassGroup", "ClassGroup")
                        .WithMany()
                        .HasForeignKey("ClassGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassGroup");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.ClassGroupTimeSlotPreference", b =>
                {
                    b.HasOne("ClassGroup", "ClassGroup")
                        .WithMany()
                        .HasForeignKey("ClassGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassGroup");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.OrganizationSchedulingPreferences", b =>
                {
                    b.HasOne("TTOptimizer.Web.Models.Domain.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.RoomTimeSlotPreference", b =>
                {
                    b.HasOne("Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.ScheduleConstraint", b =>
                {
                    b.HasOne("TTOptimizer.Web.Models.Domain.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.StudentGroup", b =>
                {
                    b.HasOne("ClassGroup", "ClassGroup")
                        .WithMany("StudentGroups")
                        .HasForeignKey("ClassGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TTOptimizer.Web.Models.Domain.StudentGroupDivision", "Division")
                        .WithMany("StudentGroups")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TTOptimizer.Web.Models.Domain.Organization", "Organization")
                        .WithMany("StudentGroups")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassGroup");

                    b.Navigation("Division");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.StudentGroupDivision", b =>
                {
                    b.HasOne("ClassGroup", "ClassGroup")
                        .WithMany()
                        .HasForeignKey("ClassGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTOptimizer.Web.Models.Domain.Organization", "Organization")
                        .WithMany("StudentGroupDivisions")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassGroup");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.StudentGroupMember", b =>
                {
                    b.HasOne("TTOptimizer.Web.Models.Domain.StudentGroup", "MemberGroup")
                        .WithMany("MemberOf")
                        .HasForeignKey("MemberGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TTOptimizer.Web.Models.Domain.StudentGroup", "StudentGroup")
                        .WithMany("Members")
                        .HasForeignKey("StudentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemberGroup");

                    b.Navigation("StudentGroup");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.SubjectSchedulingPreferences", b =>
                {
                    b.HasOne("Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.SubjectTimeSlotPreference", b =>
                {
                    b.HasOne("Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.TeacherSchedulingPreferences", b =>
                {
                    b.HasOne("Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.TeacherTimeSlotPreference", b =>
                {
                    b.HasOne("Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Teacher", b =>
                {
                    b.HasOne("TTOptimizer.Web.Models.Domain.AppUser", null)
                        .WithMany("Teachers")
                        .HasForeignKey("AppUserId");

                    b.HasOne("TTOptimizer.Web.Models.Domain.Organization", "Organization")
                        .WithMany("Teachers")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ClassGroup", b =>
                {
                    b.Navigation("StudentGroups");
                });

            modelBuilder.Entity("OptimizationRun", b =>
                {
                    b.Navigation("ScheduledLessons");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.AppUser", b =>
                {
                    b.Navigation("AppUserOrganizations");

                    b.Navigation("ClassGroups");

                    b.Navigation("LessonRequirements");

                    b.Navigation("OptimizationRuns");

                    b.Navigation("Rooms");

                    b.Navigation("Subjects");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.Building", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.Organization", b =>
                {
                    b.Navigation("AppUserOrganizations");

                    b.Navigation("Buildings");

                    b.Navigation("ClassGroups");

                    b.Navigation("LessonRequirements");

                    b.Navigation("OptimizationRuns");

                    b.Navigation("Rooms");

                    b.Navigation("StudentGroupDivisions");

                    b.Navigation("StudentGroups");

                    b.Navigation("Subjects");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.StudentGroup", b =>
                {
                    b.Navigation("MemberOf");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("TTOptimizer.Web.Models.Domain.StudentGroupDivision", b =>
                {
                    b.Navigation("StudentGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
