CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE TABLE "AppUsers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserName" character varying(200) NOT NULL,
        "DisplayName" character varying(200) NOT NULL,
        CONSTRAINT "PK_AppUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE TABLE "Organizations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(200) NOT NULL,
        CONSTRAINT "PK_Organizations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE TABLE "AppUserOrganizations" (
        "AppUserId" integer NOT NULL,
        "OrganizationId" integer NOT NULL,
        "Role" character varying(50) NOT NULL,
        CONSTRAINT "PK_AppUserOrganizations" PRIMARY KEY ("AppUserId", "OrganizationId"),
        CONSTRAINT "FK_AppUserOrganizations_AppUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AppUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AppUserOrganizations_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE TABLE "ClassGroups" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" integer NOT NULL,
        "Name" character varying(100) NOT NULL,
        "AppUserId" integer,
        CONSTRAINT "PK_ClassGroups" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ClassGroups_AppUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AppUsers" ("Id"),
        CONSTRAINT "FK_ClassGroups_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE TABLE "OptimizationRuns" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" integer NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "Success" boolean NOT NULL,
        "InitialPenalty" integer NOT NULL,
        "BestPenalty" integer NOT NULL,
        "AppUserId" integer,
        CONSTRAINT "PK_OptimizationRuns" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OptimizationRuns_AppUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AppUsers" ("Id"),
        CONSTRAINT "FK_OptimizationRuns_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE TABLE "Rooms" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" integer NOT NULL,
        "Name" character varying(100) NOT NULL,
        "AppUserId" integer,
        CONSTRAINT "PK_Rooms" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Rooms_AppUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AppUsers" ("Id"),
        CONSTRAINT "FK_Rooms_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE TABLE "Subjects" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" integer NOT NULL,
        "Name" character varying(200) NOT NULL,
        "AppUserId" integer,
        CONSTRAINT "PK_Subjects" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Subjects_AppUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AppUsers" ("Id"),
        CONSTRAINT "FK_Subjects_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE TABLE "Teachers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" integer NOT NULL,
        "Name" character varying(200) NOT NULL,
        "AppUserId" integer,
        CONSTRAINT "PK_Teachers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Teachers_AppUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AppUsers" ("Id"),
        CONSTRAINT "FK_Teachers_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE TABLE "LessonRequirements" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" integer NOT NULL,
        "ClassGroupId" integer NOT NULL,
        "SubjectId" integer NOT NULL,
        "TeacherId" integer NOT NULL,
        "HoursPerWeek" integer NOT NULL,
        "AppUserId" integer,
        CONSTRAINT "PK_LessonRequirements" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LessonRequirements_AppUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AppUsers" ("Id"),
        CONSTRAINT "FK_LessonRequirements_ClassGroups_ClassGroupId" FOREIGN KEY ("ClassGroupId") REFERENCES "ClassGroups" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_LessonRequirements_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_LessonRequirements_Subjects_SubjectId" FOREIGN KEY ("SubjectId") REFERENCES "Subjects" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_LessonRequirements_Teachers_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES "Teachers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE TABLE "ScheduledLessons" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OptimizationRunId" integer NOT NULL,
        "Day" integer NOT NULL,
        "LessonNumber" integer NOT NULL,
        "ClassGroupId" integer NOT NULL,
        "SubjectId" integer NOT NULL,
        "TeacherId" integer NOT NULL,
        "RoomId" integer NOT NULL,
        CONSTRAINT "PK_ScheduledLessons" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ScheduledLessons_ClassGroups_ClassGroupId" FOREIGN KEY ("ClassGroupId") REFERENCES "ClassGroups" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ScheduledLessons_OptimizationRuns_OptimizationRunId" FOREIGN KEY ("OptimizationRunId") REFERENCES "OptimizationRuns" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ScheduledLessons_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ScheduledLessons_Subjects_SubjectId" FOREIGN KEY ("SubjectId") REFERENCES "Subjects" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ScheduledLessons_Teachers_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES "Teachers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE INDEX "IX_AppUserOrganizations_OrganizationId" ON "AppUserOrganizations" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE UNIQUE INDEX "IX_AppUsers_UserName" ON "AppUsers" ("UserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE INDEX "IX_ClassGroups_AppUserId" ON "ClassGroups" ("AppUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE INDEX "IX_ClassGroups_OrganizationId" ON "ClassGroups" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE INDEX "IX_LessonRequirements_AppUserId" ON "LessonRequirements" ("AppUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE INDEX "IX_LessonRequirements_ClassGroupId" ON "LessonRequirements" ("ClassGroupId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE INDEX "IX_LessonRequirements_OrganizationId" ON "LessonRequirements" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE INDEX "IX_LessonRequirements_SubjectId" ON "LessonRequirements" ("SubjectId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE INDEX "IX_LessonRequirements_TeacherId" ON "LessonRequirements" ("TeacherId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE INDEX "IX_OptimizationRuns_AppUserId" ON "OptimizationRuns" ("AppUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE INDEX "IX_OptimizationRuns_OrganizationId" ON "OptimizationRuns" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE INDEX "IX_Rooms_AppUserId" ON "Rooms" ("AppUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE INDEX "IX_Rooms_OrganizationId" ON "Rooms" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE INDEX "IX_ScheduledLessons_ClassGroupId" ON "ScheduledLessons" ("ClassGroupId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE INDEX "IX_ScheduledLessons_OptimizationRunId" ON "ScheduledLessons" ("OptimizationRunId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE INDEX "IX_ScheduledLessons_RoomId" ON "ScheduledLessons" ("RoomId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE INDEX "IX_ScheduledLessons_SubjectId" ON "ScheduledLessons" ("SubjectId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE INDEX "IX_ScheduledLessons_TeacherId" ON "ScheduledLessons" ("TeacherId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE INDEX "IX_Subjects_AppUserId" ON "Subjects" ("AppUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE INDEX "IX_Subjects_OrganizationId" ON "Subjects" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE INDEX "IX_Teachers_AppUserId" ON "Teachers" ("AppUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    CREATE INDEX "IX_Teachers_OrganizationId" ON "Teachers" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707143716_InitialDatabase') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260707143716_InitialDatabase', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715164132_AddScheduleConstraints') THEN
    CREATE TABLE "ScheduleConstraints" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" integer NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Description" character varying(1000),
        "ConstraintType" character varying(100) NOT NULL,
        "TargetType" character varying(100) NOT NULL,
        "TargetId" integer NOT NULL,
        "IsHard" boolean NOT NULL DEFAULT TRUE,
        "Weight" integer NOT NULL DEFAULT 100,
        "DayOfWeek" integer,
        "SlotNumber" integer,
        "Value" character varying(500),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_ScheduleConstraints" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ScheduleConstraints_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715164132_AddScheduleConstraints') THEN
    CREATE INDEX "IX_ScheduleConstraints_OrganizationId" ON "ScheduleConstraints" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715164132_AddScheduleConstraints') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260715164132_AddScheduleConstraints', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723094656_AddTeacherNumberAliasAndInfo') THEN
    ALTER TABLE "Teachers" ADD "Alias" character varying(30) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723094656_AddTeacherNumberAliasAndInfo') THEN
    ALTER TABLE "Teachers" ADD "Info" character varying(2000);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723094656_AddTeacherNumberAliasAndInfo') THEN
    ALTER TABLE "Teachers" ADD "TeacherNumber" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723094656_AddTeacherNumberAliasAndInfo') THEN
    WITH numbered_teachers AS
    (
        SELECT
            "Id",
            ROW_NUMBER() OVER
            (
                PARTITION BY "OrganizationId"
                ORDER BY "Id"
            ) AS teacher_number
        FROM "Teachers"
    )
    UPDATE "Teachers" AS teacher
    SET
        "TeacherNumber" = numbered.teacher_number,
        "Alias" = 'T' || numbered.teacher_number
    FROM numbered_teachers AS numbered
    WHERE teacher."Id" = numbered."Id";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723094656_AddTeacherNumberAliasAndInfo') THEN
    CREATE UNIQUE INDEX "IX_Teachers_OrganizationId_Alias" ON "Teachers" ("OrganizationId", "Alias");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723094656_AddTeacherNumberAliasAndInfo') THEN
    CREATE UNIQUE INDEX "IX_Teachers_OrganizationId_TeacherNumber" ON "Teachers" ("OrganizationId", "TeacherNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723094656_AddTeacherNumberAliasAndInfo') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260723094656_AddTeacherNumberAliasAndInfo', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723120014_AddClassGroupDetails') THEN
    DROP INDEX "IX_ClassGroups_OrganizationId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723120014_AddClassGroupDetails') THEN
    ALTER TABLE "ClassGroups" ALTER COLUMN "Name" TYPE character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723120014_AddClassGroupDetails') THEN
    ALTER TABLE "ClassGroups" ADD "DefaultRoomId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723120014_AddClassGroupDetails') THEN
    ALTER TABLE "ClassGroups" ADD "HomeroomTeacherId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723120014_AddClassGroupDetails') THEN
    ALTER TABLE "ClassGroups" ADD "Info" character varying(2000);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723120014_AddClassGroupDetails') THEN
    CREATE INDEX "IX_ClassGroups_DefaultRoomId" ON "ClassGroups" ("DefaultRoomId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723120014_AddClassGroupDetails') THEN
    CREATE INDEX "IX_ClassGroups_HomeroomTeacherId" ON "ClassGroups" ("HomeroomTeacherId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723120014_AddClassGroupDetails') THEN
    CREATE UNIQUE INDEX "IX_ClassGroups_OrganizationId_Name" ON "ClassGroups" ("OrganizationId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723120014_AddClassGroupDetails') THEN
    ALTER TABLE "ClassGroups" ADD CONSTRAINT "FK_ClassGroups_Rooms_DefaultRoomId" FOREIGN KEY ("DefaultRoomId") REFERENCES "Rooms" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723120014_AddClassGroupDetails') THEN
    ALTER TABLE "ClassGroups" ADD CONSTRAINT "FK_ClassGroups_Teachers_HomeroomTeacherId" FOREIGN KEY ("HomeroomTeacherId") REFERENCES "Teachers" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723120014_AddClassGroupDetails') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260723120014_AddClassGroupDetails', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723140507_AddRoomSubjectConstraints') THEN
    DROP INDEX "IX_Rooms_OrganizationId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723140507_AddRoomSubjectConstraints') THEN
    ALTER TABLE "Rooms" ADD "Info" character varying(2000);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723140507_AddRoomSubjectConstraints') THEN
    ALTER TABLE "Rooms" ADD "PreferredSubjectId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723140507_AddRoomSubjectConstraints') THEN
    ALTER TABLE "Rooms" ADD "RestrictedToSubjectId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723140507_AddRoomSubjectConstraints') THEN
    CREATE UNIQUE INDEX "IX_Rooms_OrganizationId_Name" ON "Rooms" ("OrganizationId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723140507_AddRoomSubjectConstraints') THEN
    CREATE INDEX "IX_Rooms_PreferredSubjectId" ON "Rooms" ("PreferredSubjectId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723140507_AddRoomSubjectConstraints') THEN
    CREATE INDEX "IX_Rooms_RestrictedToSubjectId" ON "Rooms" ("RestrictedToSubjectId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723140507_AddRoomSubjectConstraints') THEN
    ALTER TABLE "Rooms" ADD CONSTRAINT "FK_Rooms_Subjects_PreferredSubjectId" FOREIGN KEY ("PreferredSubjectId") REFERENCES "Subjects" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723140507_AddRoomSubjectConstraints') THEN
    ALTER TABLE "Rooms" ADD CONSTRAINT "FK_Rooms_Subjects_RestrictedToSubjectId" FOREIGN KEY ("RestrictedToSubjectId") REFERENCES "Subjects" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723140507_AddRoomSubjectConstraints') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260723140507_AddRoomSubjectConstraints', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723151556_AddSubjectDetails') THEN
    DROP INDEX "IX_Subjects_OrganizationId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723151556_AddSubjectDetails') THEN
    ALTER TABLE "Subjects" ALTER COLUMN "Name" TYPE character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723151556_AddSubjectDetails') THEN
    ALTER TABLE "Subjects" ADD "Info" character varying(2000);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723151556_AddSubjectDetails') THEN
    CREATE UNIQUE INDEX "IX_Subjects_OrganizationId_Name" ON "Subjects" ("OrganizationId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723151556_AddSubjectDetails') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260723151556_AddSubjectDetails', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260724084833_AddResourceUnavailability') THEN
    CREATE TABLE "ClassGroupUnavailabilities" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ClassGroupId" integer NOT NULL,
        "DayIndex" integer NOT NULL,
        "SlotIndex" integer NOT NULL,
        CONSTRAINT "PK_ClassGroupUnavailabilities" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ClassGroupUnavailabilities_ClassGroups_ClassGroupId" FOREIGN KEY ("ClassGroupId") REFERENCES "ClassGroups" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260724084833_AddResourceUnavailability') THEN
    CREATE TABLE "RoomUnavailabilities" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoomId" integer NOT NULL,
        "DayIndex" integer NOT NULL,
        "SlotIndex" integer NOT NULL,
        CONSTRAINT "PK_RoomUnavailabilities" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RoomUnavailabilities_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260724084833_AddResourceUnavailability') THEN
    CREATE TABLE "TeacherUnavailabilities" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TeacherId" integer NOT NULL,
        "DayIndex" integer NOT NULL,
        "SlotIndex" integer NOT NULL,
        CONSTRAINT "PK_TeacherUnavailabilities" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_TeacherUnavailability_DayIndex" CHECK ("DayIndex" >= 0 AND "DayIndex" <= 4),
        CONSTRAINT "FK_TeacherUnavailabilities_Teachers_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES "Teachers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260724084833_AddResourceUnavailability') THEN
    CREATE UNIQUE INDEX "IX_ClassGroupUnavailabilities_ClassGroupId_DayIndex_SlotIndex" ON "ClassGroupUnavailabilities" ("ClassGroupId", "DayIndex", "SlotIndex");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260724084833_AddResourceUnavailability') THEN
    CREATE UNIQUE INDEX "IX_RoomUnavailabilities_RoomId_DayIndex_SlotIndex" ON "RoomUnavailabilities" ("RoomId", "DayIndex", "SlotIndex");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260724084833_AddResourceUnavailability') THEN
    CREATE UNIQUE INDEX "IX_TeacherUnavailabilities_TeacherId_DayIndex_SlotIndex" ON "TeacherUnavailabilities" ("TeacherId", "DayIndex", "SlotIndex");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260724084833_AddResourceUnavailability') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260724084833_AddResourceUnavailability', '9.0.4');
    END IF;
END $EF$;
COMMIT;

